cms/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from cms_app import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cms_app.urls')),
    path('sortBycatagory/<int:cat_id>/',views.sort, name='sort'),
    re_path(r'^tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cms_app/urls.py
from django.urls import path
from cms_app import views

app_name = 'cms_app'

urlpatterns = [
    path('',views.index, name='index'),
    path('post/<int:id>', views.post, name = 'user_post'),
    path('register/', views.register, name ='register'),
    path('login/', views.user_login, name ='user_login'),
    path('sort/<str:by>/<int:id>', views.post_sort, name ='post_sort'),



    path('admin_home/', views.admin_index, name = "admin_index"),
    path('admin_home/category/', views.admin_category, name = 'category'),
    path('admin_home/category/delete/<int:id>', views.cat_delete, name = 'cat_delete'),
    path('admin_home/category/edit/<int:id>', views.cat_edit, name = 'cat_edit'),
    path('admin_home/post/', views.admin_post, name='post'),
    path('admin_home/post/delete/<int:id>', views.post_delete, name='post_delete'),
    path('admin_home/post/edit/<int:id>', views.post_edit, name='post_edit'),
    path('admin_home/post/add/', views.post_add, name='post_add'),
    path('admin_home/comments/', views.comment, name='comment'),
    path('admin_home/comments/<int:id>', views.comment_delete, name='comment_delete'),
    path('admin_home/comments/<int:id>/<str:status>', views.comment_approval, name='comment_approval'),
    path('admin_home/users/', views.users, name ='SeeUsers'),
    path('admin_home/users/add/', views.user_add, name ='user_add'),
    path('admin_home/users/<int:id>/role/<int:isAdmin>/', views.user_role, name ='user_role'),
    path('admin_home/users/<int:id>/delete', views.user_delete, name ='user_delete'),
    path('admin_home/user_profile/', views.user_profile, name ='user_profile'),
    path('admin_home/logout/', views.user_logout, name ='user_logout'),


]

cms_app/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User


# Create your models here.
class Catagory(models.Model):
    cat_id = models.AutoField(primary_key=True)
    cat_title = models.CharField(max_length=256)

    def __str__(self):
        return self.cat_title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    user_image = models.ImageField(upload_to = 'users_pics', blank = True,null=True,default=None)
    user_isAdmin = models.BooleanField(default = False)

    def __str__(self):
        return self.user.username


class Post(models.Model):
    post_id = models.AutoField(primary_key=True)
    post_cat_id = models.ForeignKey(Catagory, on_delete = models.SET_NULL, null =True)
    post_title = models.CharField(max_length =256)
    post_author = models.ForeignKey(User, on_delete=models.SET_NULL,  null =True)
    post_date = models.DateField(auto_now_add=True)
    post_image = models.ImageField(upload_to = 'posts_pics', blank = True)
    post_content = models.TextField()
    post_tags = models.CharField(max_length=256, blank = True)
    post_comment_count = models.IntegerField(blank=True, default=0)
    post_status = models.CharField(max_length=256)

    def __str__(self):
        return self.post_title

class Comment(models.Model):
    com_id= models.AutoField(primary_key=True)
    com_post_id = models.ForeignKey(Post, on_delete = models.CASCADE)
    com_author = models.ForeignKey(User,on_delete = models.SET_NULL, null = True)
    com_content = models.TextField()
    com_status = models.CharField(max_length=256)
    com_date = models.DateField(auto_now_add=True)

cms_app/forms.py
from django import forms
from cms_app.models import UserProfile, Comment, Catagory, Post
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Catagory
        fields =['cat_title',]
        widgets = {'cat_title':forms.TextInput(attrs={'class':'form-control','name':'cat_title',})}

class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['post_id', 'post_date', 'post_comment_count']

class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude =['post_id',]

class RegisterUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields =['username', 'email', 'first_name', 'last_name', 'password']
        widgets ={'password':forms.PasswordInput()}

class RegisterUserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['user_image','user_isAdmin']

class EditUserProfile(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['user_image',]

class CommentForm(forms.ModelForm):
    class Meta:
        model =Comment
        fields = ['com_content']

cms_app/views.py
from django.contrib.auth.models import User
from math import ceil
from django.shortcuts import render
from cms_app.models import Catagory,UserProfile,Comment,Post
from cms_app.forms import CommentForm, CategoryForm, EditPostForm, AddPostForm, RegisterUserForm, RegisterUserProfileForm, EditUserProfile
from django.db.models import Q
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.http import HttpResponseRedirect, HttpResponse
from django.core.paginator import Paginator
# Create your views here.

def index(request):
    posts_per_page =2
    catagories = Catagory.objects.all().order_by('cat_title')
    cat_half =ceil(catagories.count()/2)
    cat_first_half = catagories[0:cat_half]
    cat_second_half = catagories[cat_half:catagories.count()]
    posts = Post.objects.filter(post_status='published')[0:posts_per_page]
    count = ceil(Post.objects.filter(post_status='published').count()/posts_per_page)

    if 'page' in request.GET:
        page = int(request.GET['page'])
        posts = Post.objects.filter(post_status='published')[(page-1)*posts_per_page:(page)*posts_per_page]

    if 'search' in request.POST:
        search_item = request.POST['search']
        posts = Post.objects.filter(Q(post_title__icontains = search_item)|
                                    Q(post_content__icontains = search_item)|
                                    Q(post_tags__icontains = search_item))

    post_list = Post.objects.filter(post_status='published')
    paginator = Paginator(post_list,posts_per_page)
    page = request.GET.get('page')
    contacts = paginator.get_page(page)

    dict ={
        'catagories':catagories,
        'cat_first_half':cat_first_half,
        'cat_second_half':cat_second_half,
        'posts':posts,
        'range':range(1,count+1),
        'contacts':contacts,
    }

    return render(request,'cms_app/index.html',dict)

def sort(request, cat_id):
        catagories = Catagory.objects.all().order_by('cat_title')
        posts = Post.objects.filter(post_cat_id = cat_id,post_status='published')
        cat_half =ceil(catagories.count()/2)
        cat_first_half = catagories[0:cat_half]
        cat_second_half = catagories[cat_half:catagories.count()]



        dict ={
                'catagories':catagories,
                'cat_first_half':cat_first_half,
                'cat_second_half':cat_second_half,
                'posts':posts,
        }
        return render(request,'cms_app/index.html',dict)

def post_sort(request, by, id):
    if by == 'author':
        posts = Post.objects.filter(post_author = id)

    dict = {'posts':posts}

    return render(request,'cms_app/index.html',dict)

def register(request):

    if request.POST:
        UserForm = RegisterUserForm(request.POST)
        ProfileForm =RegisterUserProfileForm(request.POST, request.FILES)

        if UserForm.is_valid() and ProfileForm.is_valid():
            user=UserForm.save()
            user.set_password(user.password)
            user.save()

            profile=ProfileForm.save(commit=False)
            profile.user = user

            if 'user_image' in request.FILES:
                profile.user_image = request.FILES['user_image']

            profile.save()
            login(request, user)
            request.session['user_id'] = user.id
            return redirect('cms_app:admin_index')
    else:
        UserForm = RegisterUserForm()
        ProfileForm = RegisterUserProfileForm()
    return render(request, 'cms_app/registration.html', {'form':UserForm,'form_profile':ProfileForm,})


def post(request, id):
    catagories = Catagory.objects.order_by('cat_title')
    post = Post.objects.get(post_id=id)
    comments = Comment.objects.filter(com_post_id=id, com_status = 'approved')
    commentForm = CommentForm()
    warning = "None"

    if request.method=="POST":
        if request.user.is_authenticated:
            commentForm = CommentForm(request.POST)
            if commentForm.is_valid():
                comment = commentForm.save(commit=False)
                comment.com_author = request.user
                comment.com_post_id = post
                comment.com_status = 'disapproved'
                comment.save()
                post.post_comment_count = post.post_comment_count+1;
                post.save()
        else:
            warning = "Only signed users can comment"

    commentForm = CommentForm()
    dict ={
        'catagories':catagories,
        'post':post,
        'comments':comments,
        'commentForm':commentForm,
        'warning':warning
        }

    return render(request,'cms_app/post.html',dict)

@login_required(login_url='/login/')
def admin_index(request):
    dict={}
    if request.session.has_key('user_id'):

        user_id = request.session['user_id']
        user = User.objects.get(pk=user_id)
        user_count = User.objects.all().count()
        com_count = Comment.objects.all().count()
        cat_count = Catagory.objects.all().count()
        post_count = Post.objects.all().count()
        active_post_count = Post.objects.filter(post_status = 'published').count()
        draft_post_count = Post.objects.filter(post_status = 'unpublished').count()
        pending_comments = Comment.objects.filter(com_status = 'disapproved').count()
        subscribers_count = UserProfile.objects.filter(user_isAdmin=False).count()

        dict = {
            'user':user,
            'user_count':user_count,
            'post_count':post_count,
            'com_count':com_count,
            'cat_count':cat_count,
            'zipped_data':{'Active posts':active_post_count,
                            'Draft posts':draft_post_count,
                            'Comments':com_count,
                            'Pending comments':pending_comments,
                            'Users':user_count,
                            'Subscribers':subscribers_count,
                            'Categories':cat_count},
        }

    return render(request,'admin/admin_index.html',dict)

@login_required(login_url='/login/')
def admin_category(request):
    form = CategoryForm()
    categories = Catagory.objects.all()

    if request.method=='POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit =True)

    return render(request,'admin/category.html',{'form':form, 'categories':categories,})

@login_required(login_url='/login/')
def cat_delete(request,id):
    Catagory.objects.get(pk=id).delete()
    categories = Catagory.objects.all()
    form = CategoryForm()
    return render(request,'admin/category.html',{'form':form, 'categories':categories,})

@login_required(login_url='/login/')
def cat_edit(request,id):
    updating_cat = Catagory.objects.get(pk=id)
    categories = Catagory.objects.all()
    form = CategoryForm()

    if request.method == "POST":
        value = request.POST['cat_title']
        updating_cat.cat_title = value;
        updating_cat.save()

    dict ={
        'form':form,
        'categories':categories,
        'updating_cat':updating_cat,
    }

    return render(request,'admin/category.html',dict)

@login_required(login_url='/login/')
def admin_post(request):
    posts = Post.objects.all()
    dict = {'posts':posts,}
    return render(request,'admin/post.html',dict)

@login_required(login_url='/login/')
def post_delete(request,id):
    Post.objects.get(pk=id).delete()
    return redirect('cms_app:post')

    return admin_post(request)

@login_required(login_url='/login/')
def post_edit(request,id):
    updating_post = Post.objects.get(pk=id)
    form = EditPostForm(instance = updating_post)

    if request.method == "POST":
        form = EditPostForm(request.POST, request.FILES, instance = updating_post)
        if form.is_valid():
            form.save()
            # updating_post.post_image = request.POST['post_image']
            # updating_post.save()
            print("SAVED")
            return redirect('cms_app:post')
        else:
            print("ERROR! INVALID DATA")

    return render(request,'admin/post_edit.html',{'updating_post':updating_post,'form':form})

@login_required(login_url='/login/')
def post_add(request):
    if request.method =="POST":
        form = AddPostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            if request.POST['submit'] == 'SR':
                return redirect('cms_app:post')
            elif request.POST['submit']=='SA':
                return redirect('cms_app:post_add')
        else:
            print("INVALID DATA inserted")
    else:
        form = AddPostForm()
        dict ={'form':form,}
        return render(request, 'admin/post_add.html', dict)

@login_required(login_url='/login/')
def comment(request):
    comments = Comment.objects.all()
    return render(request,'admin/admin_comments.html',{'comments':comments})

@login_required(login_url='/login/')
def comment_delete(request,id):
    Comment.objects.get(pk=id).delete()
    return redirect('cms_app:comment')

@login_required(login_url='/login/')
def comment_approval(request,id,status):
    com =Comment.objects.get(pk=id)
    com.com_status = status
    com.save()
    return redirect('cms_app:comment')

@login_required(login_url='/login/')
def users(request):
    users = User.objects.all()
    return render(request,'admin/allusers.html',{'users':users})

@login_required(login_url='/login/')
def user_add(request):
    if request.POST:
        UserForm = RegisterUserForm(request.POST)
        ProfileForm =RegisterUserProfileForm(request.POST, request.FILES)

        if UserForm.is_valid() and ProfileForm.is_valid():
            user=UserForm.save()
            user.set_password(user.password)
            user.save()

            profile=ProfileForm.save(commit=False)
            profile.user = user

templates/cms_app/comments.html
{% load crispy_forms_tags %}
                {% if warning != "None" %}
                <div class="alert alert-warning">
                  {{warning}}
                </div>
                {% endif %}
                <!-- Comments Form -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form method="post">
                      {% csrf_token %}
                        {{commentForm|crispy }}
                        <button type="submit" class="btn btn-primary" name='submit' value="submit">Submit</button>
                    </form>
                </div>

                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->
                {% if comments %}
                {% for com in comments %}

                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="{{ com.com_author.userprofile.user_image.url }}" width="64px" height="64px">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">{{com.com_author.username}}
                            <small>Posted on {{com.com_date}}</small>
                        </h4>
                        {{com.com_content}}
                    </div>
                </div>

                {% endfor %}
                {% endif %}

templates/cms_app/index.html
<!DOCTYPE html>
{% load static %}
{% load costum_tags %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

    <!-- Navigation -->
    {% include 'cms_app/nav.html' %}

    <!-- Page Content -->
    <div class="container">

        <div class="row">
  
            <!-- Blog Entries Column -->
            <div class="col-md-8">
              {% if posts %}
                {% for post in posts %}

                <!-- First Blog Post -->

                <h2>
                    <a href="{% url 'cms_app:user_post' post.post_id %}">{{post.post_title}}</a>
                </h2>
                <p class="lead">
                    by <a href="{% url 'cms_app:post_sort' by='author' id=post.post_author.id %}">{{ post.post_author.username }}</a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span>{{post.post_date}}</p>
                <hr>
                <a href="{% url 'cms_app:user_post' post.post_id %}"> <img class="img-responsive" src="{{ post.post_image.url }}" alt=""></a>
                <hr>
                <p>
                    {% autoescape off %}
                        {{post.post_content|slice:"0:400"}}
                    {% endautoescape %}
                </p>
                <a class="btn btn-primary" href="{% url 'cms_app:user_post' id=post.post_id %}">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
                <hr>
                {% endfor %}
                {% endif %}

                <!-- Pager -->
                <ul class="pager">
                  {% if contacts.has_previous %}
                  <li>
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ contacts.previous_page_number }}">previous</a>
                  </li>
                  {% endif %}

                    {% for i in range %}
                    <li>
                        <a href="{% url 'cms_app:index' %}?page={{i}}">{{i}}</a>
                    </li>
                    {% endfor %}

                    {% if contacts.has_next %}
                    <li>
                      <a href="?page={{ contacts.next_page_number }}">next</a>
                      <a href="?page={{ contacts.paginator.num_pages }}">last &raquo;</a>
                    </li>
                    {% endif %}
                </ul>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            {% include 'cms_app/sidebar.html' %}

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->


    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

templates/cms_app/login.html
<!DOCTYPE html>
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

  {% include 'cms_app/nav.html' %}

<!-- Page Content -->
<div class="container">

<section id="login">
<div class="container">
    <div class="row">
        <div class="col-xs-4 col-xs-offset-4">
            <div class="form-wrap">
            <h1>Login</h1>

            <form action="{% url 'cms_app:user_login' %}" method="post">{% csrf_token %}
            <div class="form-group">
                <input name="username" type="text" class="form-control" placeholder="Enter Username">
            </div>
            <div class="input-group">
                <input name="password" type="password" class="form-control" placeholder="Enter Password">

                <span class="input-group-btn">
                   <button class="btn btn-primary" name="login" type="submit">Submit</button>
                </span>
            </div>
            </form>

            </div>
        </div> <!-- /.col-xs-12 -->
    </div> <!-- /.row -->
</div> <!-- /.container -->
</section>
    <hr>
    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Umbrella Corp. 2019</p>
            </div>
        </div>
        <!-- /.row -->
    </footer>

</div>
<!-- /.container -->

<!-- jQuery -->
<script src="{% static 'js/jquery.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

templates/cms_app/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'cms_app:index' %}">Home</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              {% if catagories %}
                {% for cat in catagories %}
                <li>
                    <a href="{% url 'sort' cat_id=cat.cat_id %}">{{cat.cat_title}}</a>
                </li>
                {% endfor %}
              {% endif %}
              <li>
                  <a href="{% url 'cms_app:admin_index' %}">Admin</a>
              </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

templates/cms_app/post.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/blog-home.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

  {% include 'cms_app/nav.html' %}

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">
              {% if post %}
                <!-- Blog Post -->

                <!-- Title -->
                <h1>{{post.post_title}}</h1>

                <!-- Author -->
                <p class="lead">
                    by <a href="{% url 'cms_app:post_sort' by='author' id=post.post_author.id %}">{{post.post_author.username}}</a>
                </p>

                <hr>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on {{post.post_date}}</p>

                <hr>

                <!-- Preview Image -->
                <img class="img-responsive" src="{{ post.post_image.url }}" alt="">

                <hr>
                <!-- Post Content -->
                <p>{{post.post_content}}</p>
                <hr>
            
                {% endif %}

                <!-- Blog Comments -->
                {% include 'cms_app/comments.html' %}

            </div>

            <!-- Blog Sidebar Widgets Column -->
            {% include 'cms_app/sidebar.html' %}

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>

</html>

templates/cms_app/sidebar.html
<div class="col-md-4">

    <!-- Blog Search Well -->
    <div class="well">
        <h4>Blog Search</h4>
        <form method="POST" action="{% url 'cms_app:index' %}">{% csrf_token %}
        <div class="input-group">

            <input name="search" type="text" class="form-control" value="{{request.GET.search}}">
            <span class="input-group-btn">
                <button name="submit" class="btn btn-default" type="submit">
                    <span class="glyphicon glyphicon-search"></span>
            </button>
            </span>

        </div>
        </form><!--search form-->
        <!-- /.input-group -->
      </div>

    <div class="well">
      <h4>Login</h4>

         <form action="{% url 'cms_app:user_login' %}" method="post">{% csrf_token %}
         <div class="form-group">
             <input name="username" type="text" class="form-control" placeholder="Enter Username">
         </div>
         <div class="input-group">
             <input name="password" type="password" class="form-control" placeholder="Enter Password">

             <span class="input-group-btn">
                <button class="btn btn-primary" name="login" type="submit">Submit</button>
             </span>
         </div>
         </form><!--search form-->
         <!-- /.input-group -->
         <p><br>Not registered yet? <a href="{% url 'cms_app:register' %}">Click here</a> to register</p>
    </div>

    <!-- Blog Categories Well -->
    <div class="well">
        <h4>Blog Categories</h4>
        <div class="row">
          <div class="col-lg-6">
              <ul class="list-unstyled">
                {% if cat_first_half %}
                  {% for cat in cat_first_half %}
                  <li>
                    <a href="{% url 'sort' cat_id=cat.cat_id %}">{{cat.cat_title}}</a>
                  </li>
                  {% endfor %}
                {% endif %}
          </div>

            <!-- /.col-lg-6 -->
            <div class="col-lg-6">
                <ul class="list-unstyled">
                  {% if cat_second_half %}
                    {% for cat in cat_second_half %}
                    <li>
                      <a href="{% url 'sort' cat_id=cat.cat_id %}">{{cat.cat_title}}</a>
                    </li>
                    {% endfor %}
                  {% endif %}
            </div>

            <!-- /.col-lg-6 -->
        </div>
        <!-- /.row -->
    </div>

</div>